### ISSUE TITLE
"Jump to selection" missing

### ISSUE THREAD

**Issue by rugk** [brettz9/jump-to-anchor#10]
The new WebExtension version is missing the "Jump to selection" mode, where – only if you had something selected – another menu entry would appear stating you can also jump to the selection instead of current click position.

/cc @jomo

**Comment by rugk** [comment]
Or wait … it is implemented, but not a different context menu item?

**Comment by brettz9** [comment]
Yes, if you make a selection, it will use that. I believe I had added an additional context menu item because I found myself sometimes having an accidental selection in the page, but unless others start having this problem, I think it may be better to rely on this behavior which @jomo reintroduced as it makes less context menu clutter. What do you think?

**Comment by rugk** [comment]
I experienced this problem. So IMHO at least the text in the context menu item should change depending on what it now uses to choose the anchor from.
Or you could just make an option, which toggles this behavior. Something like "Use additional context menu entry for jumping to a selection.".

**Comment by brettz9** [comment]
I've pushed such an option to split the context menu items, and it is now published on [AMO](https://addons.mozilla.org/en-US/firefox/addon/jump-to-anchor/) and the [Chrome Web Store](https://chrome.google.com/webstore/detail/jump-to-anchor/fhbjjkmbahpmoegppmljagmakkeomlmb). Feel free to comment further if this doesn't meet your needs.

Incidentally, it'd also be nice to have reviews on the Chrome Web Store if anyone cares to try it there.
