### ISSUE TITLE
Context menu entry shown twice

### ISSUE THREAD

**Issue by rugk** [brettz9/jump-to-anchor#6]
Sometimes the context menu entry is shown two times directly under each other.
After I click on one entry the other one disappears.

However I don't know really by what this is caused, but it happens regularly. I still have to figure out a way to reproduce this.

**Comment by brettz9** [comment]
The issue is when you have text highlighted on the page. Unfortunately the allowable contexts (at https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/context-menu#Specifying_contexts ) overlap. It is possible though that I could workaround this by avoiding the special context for selections and then just use the regular web API for detecting highlighted text. That might work. Or I could rename the menus to indicate that one item is relative to the selected text, and another one relative to where the user right-clicks.

**Comment by rugk** [comment]
Okay, at least good to know that this is a known-issue.

**Comment by brettz9** [comment]
I've addressed this in 0.5.2 by distinguishing the text for click point or highlighted selections as the reference point (waiting on AMO approval).
